
INSERT INTO `beritas` (`id`, `judul`, `kategori_berita_id`, `tanggal_terbit`, `excerpts`, `slug`, `author`, `isi_berita`, `created_at`, `updated_at`) VALUES
(1, 'HADIRI RAPAT UMUM RUPS PD BPR SE-SULTRA, GUBERNUR HARAPKAN PENINGKATAN PELAYANAN KREDIT', 3, '2023-05-02 16:00:00', 'Perumda Utama Sultra menghadiri Workshop dan RUPS PD BPR 2023. Perwakilan BPKP Provinsi Sulawesi Tenggara bidang Akuntan Negara menyelenggarakan Kegiatan Workshop Pelaksanaan Evaluasi Kinerja, Manajemen Risiko, dan Penguatan Satuan Pengawas Intern (SPI) BUMD diikuti oleh 7 BUMD se-Sulawesi Tenggara tanggal 14-15 September 2022 secara daring dan luring.', 'perumda-utama-hadiri-rups-pd-bpr-sesultra-2023', 'Muhammad Rais', '<p>Perwakilan BPKP Provinsi Sulawesi Tenggara bidang Akuntan Negara menyelenggarakan Kegiatan Workshop Pelaksanaan Evaluasi Kinerja, Manajemen Risiko, dan Penguatan Satuan Pengawas Intern (SPI) BUMD diikuti oleh 7 BUMD se-Sulawesi Tenggara tanggal 14-15 September 2022 secara daring dan luring.</p> <p>Kegiatan luring dilaksanakan di ruangan Library Cafe Perwakilan BPKP Provinsi Sulawesi Tenggara. Kegiatan ini bertujuan untuk mensosialisasikan mekanisme dan parameter penilaian kinerja BUMD, pengenalan Manajemen Risiko, dan penguatan SPI. Hadir secara langsung Direksi Perumda Utama Sultra Ansar Andi Said Jakile, dan Direktur Utama Perumda Kota Kendari Munir Madjid, dan Direktur Operasional Perumda Kota Kendari Agung Hari Bowo.</p>, <p>Terima kasih banyak sebelumnya pak Wahyu dan team BPKP atas terselenggaranya workshop ini, sangat bermanfaat. Salam sehat dan sukses buat kita semua ungkap Agung Hari Bowo, Direktur Operasional Perumda Kota Kendari.</p> <p>Perumda juga mengungkapkan kegiatan semacam ini dapat berlanjut sehingga tata kelola dan kinerja BUMD/Perumda menjadi lebih baik.</p>', '2023-05-02 02:52:44', '2023-05-02 02:52:44'),
(2, 'MENYAMBUT TAHUN INVESTASI 2023, PERUMDA UTAMA MENYIAPKAN SEJUMLAH PROPOSAL KERJASAMA YANG SANGAT MENARIK MINAT INVESTOR', 4, '2023-05-02 11:13:25', 'Perumda Utama Sultra melalui Direktur Keuangan H.A. Ansar Said Djakile menyampaikan pada awak media tentang sejumlah proposal kerjasama yang telah dilengkapi dengan study kelayakan yang sangat lengkap, dan berharap bahwa investor seluruh Indonesia dapat segera melakukan kerjasama investasi pada berbagai sektor yang ditawarkan', 'menyambut-tahun-investasi-2023-perumda-utama-mengajak-investor', 'Muhammad Rais', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, perferendis dolorem sapiente ipsam nihil recusandae error! Fugiat iste a, vero officia odit nam, reiciendis, esse laboriosam expedita praesentium corrupti quisquam quidem? At, nesciunt facere vero incidunt deleniti nisi tempore laborum quo asperiores repudiandae aperiam accusantium neque ea dolore a beatae libero perspiciatis pariatur laudantium inventore quae hic! Suscipit molestias itaque facilis. Quam, maiores! Quae, quo ipsam, dicta ex dolorem nobis tempore, impedit eum soluta eveniet adipisci quos! Eos quaerat mollitia asperiores eligendi placeat iure accusantium nulla officiis culpa quae esse, vero error est perspiciatis sapiente pariatur consequatur recusandae earum repudiandae? Corrupti modi consequatur facere aliquam tenetur! Eius quia excepturi esse vitae quod animi, obcaecati voluptates atque, aut enim mollitia? Porro quaerat iusto sunt, eaque ut veritatis illo laboriosam molestiae quo animi nostrum. Hic repellendus totam doloribus exercitationem dolor voluptas rerum impedit quo, neque numquam natus ducimus quaerat sed expedita dolores repudiandae quas rem animi non modi, nesciunt atque fugiat minima iure? Rerum optio delectus consequuntur numquam neque, nisi suscipit aliquid. Temporibus harum ad animi fugit, ipsum expedita quidem ex quae officia distinctio eligendi officiis hic rem quo, atque, ipsa nam quibusdam velit quam! Natus est quibusdam iste, exercitationem laudantium dignissimos.</p>', '2023-05-02 02:58:08', '2023-05-02 02:58:08'),
(3, 'GUBERNUR SULAWESI TENGGARA MENINJAU PERSIAPAN PEMBANGUNAN SILO BAHAN BAKAR SOLAR NELAYAN YANG DITINGKATKAN KAPASITASNYA OLEH PERUMDA UTAMA', 3, '2023-05-02 11:13:25', 'Kunjungan Gubernur Sulawesi Tenggara selaku Komisaris Utama Perumda Sultra, meninjau perkembangan pembangunan silo dan rencana peresmian yangkan dilakukan semester awal 2023. Pada kesempatan tersebut. Dirut Perumda Utama Sultra menyerahkan berkas laporan evaluasi pembangunan yang telah berjalan hampir setahun kepada Pemerintah Daerah Sulawesi Tenggara', 'gubernur-sultra-meninjau-pembangunan-silo-2023-januari', 'Minarni', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, perferendis dolorem sapiente ipsam nihil recusandae error! Fugiat iste a, vero officia odit nam, reiciendis, esse laboriosam expedita praesentium corrupti quisquam quidem? At, nesciunt facere vero incidunt deleniti nisi tempore laborum quo asperiores repudiandae aperiam accusantium neque ea dolore a beatae libero perspiciatis pariatur laudantium inventore quae hic! Suscipit molestias itaque facilis. </p><p> Quam, maiores! Quae, quo ipsam, dicta ex dolorem nobis tempore, impedit eum soluta eveniet adipisci quos! Eos quaerat mollitia asperiores eligendi placeat iure accusantium nulla officiis culpa quae esse, vero error est perspiciatis sapiente pariatur consequatur recusandae earum repudiandae? Corrupti modi consequatur facere aliquam tenetur! Eius quia excepturi esse vitae quod animi, obcaecati voluptates atque, aut enim mollitia? Porro quaerat iusto sunt, eaque ut veritatis illo laboriosam molestiae quo animi nostrum. </p><p>    Hic repellendus totam doloribus exercitationem dolor voluptas rerum impedit quo, neque numquam natus ducimus quaerat sed expedita dolores repudiandae quas rem animi non modi, nesciunt atque fugiat minima iure? Rerum optio delectus consequuntur numquam neque, nisi suscipit aliquid. Temporibus harum ad animi fugit, ipsum expedita quidem ex quae officia distinctio eligendi officiis hic rem quo, atque, ipsa nam quibusdam velit quam! Natus est quibusdam iste, exercitationem laudantium dignissimos.</p>', '2023-05-02 03:02:43', '2023-05-02 03:02:43'),
(4, 'PENGUMUNAN HASIL UJIAN PENERIMAAN PEGAWAI DI LINGKUP PERUMDA UTAMA SULTRA', 5, '2023-05-02 11:13:25', 'Daftar hasil penerimaan pegawai di lingkup Perumda Utama Sultra. Download pdf dan syarat pendaftaran ulang serta ketentuan perusahaan', 'pengumuman-hasil-penerimaan-pegawai-perumda-2023', 'Minarni', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, perferendis dolorem sapiente ipsam nihil recusandae error! Fugiat iste a, vero officia odit nam, reiciendis, esse laboriosam expedita praesentium corrupti quisquam quidem? At, nesciunt facere vero incidunt deleniti nisi tempore laborum quo asperiores repudiandae aperiam accusantium neque ea dolore a beatae libero perspiciatis pariatur laudantium inventore quae hic! Suscipit molestias itaque facilis. </p><p> Quam, maiores! Quae, quo ipsam, dicta ex dolorem nobis tempore, impedit eum soluta eveniet adipisci quos! Eos quaerat mollitia asperiores eligendi placeat iure accusantium nulla officiis culpa quae esse, vero error est perspiciatis sapiente pariatur consequatur recusandae earum repudiandae? Corrupti modi consequatur facere aliquam tenetur! Eius quia excepturi esse vitae quod animi, obcaecati voluptates atque, aut enim mollitia? Porro quaerat iusto sunt, eaque ut veritatis illo laboriosam molestiae quo animi nostrum. </p><p>    Hic repellendus totam doloribus exercitationem dolor voluptas rerum impedit quo, neque numquam natus ducimus quaerat sed expedita dolores repudiandae quas rem animi non modi, nesciunt atque fugiat minima iure? Rerum optio delectus consequuntur numquam neque, nisi suscipit aliquid. Temporibus harum ad animi fugit, ipsum expedita quidem ex quae officia distinctio eligendi officiis hic rem quo, atque, ipsa nam quibusdam velit quam! Natus est quibusdam iste, exercitationem laudantium dignissimos.</p>', '2023-05-02 03:04:35', '2023-05-02 03:04:35'),
(5, 'PENGUMUMAN PENERIMAAN OUTSOURCING UNTUK SECURITY DI PT. VALE, PT.IMIP dan PT. SIP', 6, '2023-05-02 11:13:25', 'Penerimaan tenaga outsourcing security untuk beberapa mitra Perumda Utama Sultra. PT. ANTAM, PT. VALE, PT. IMIP dan PT. SIP membutuhkan 1200 orang Tenaga Kerja baru tahun 2023, dan 300 diantaranya adalah untuk bagian security (SATPAM)', 'lowongan-kerja-outsourcing-2023-satpam', 'Minarni', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, perferendis dolorem sapiente ipsam nihil recusandae error! Fugiat iste a, vero officia odit nam, reiciendis, esse laboriosam expedita praesentium corrupti quisquam quidem? At, nesciunt facere vero incidunt deleniti nisi tempore laborum quo asperiores repudiandae aperiam accusantium neque ea dolore a beatae libero perspiciatis pariatur laudantium inventore quae hic! Suscipit molestias itaque facilis. </p><p> Quam, maiores! Quae, quo ipsam, dicta ex dolorem nobis tempore, impedit eum soluta eveniet adipisci quos! Eos quaerat mollitia asperiores eligendi placeat iure accusantium nulla officiis culpa quae esse, vero error est perspiciatis sapiente pariatur consequatur recusandae earum repudiandae? Corrupti modi consequatur facere aliquam tenetur! Eius quia excepturi esse vitae quod animi, obcaecati voluptates atque, aut enim mollitia? Porro quaerat iusto sunt, eaque ut veritatis illo laboriosam molestiae quo animi nostrum. </p><p>    Hic repellendus totam doloribus exercitationem dolor voluptas rerum impedit quo, neque numquam natus ducimus quaerat sed expedita dolores repudiandae quas rem animi non modi, nesciunt atque fugiat minima iure? Rerum optio delectus consequuntur numquam neque, nisi suscipit aliquid. Temporibus harum ad animi fugit, ipsum expedita quidem ex quae officia distinctio eligendi officiis hic rem quo, atque, ipsa nam quibusdam velit quam! Natus est quibusdam iste, exercitationem laudantium dignissimos.</p>', '2023-05-02 03:07:23', '2023-05-02 03:07:23');


ALTER TABLE `beritas`
  ADD PRIMARY KEY (`id`),
  ADD KEY `beritas_kategori_berita_id_foreign` (`kategori_berita_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `beritas`
--
ALTER TABLE `beritas`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `beritas`
--
ALTER TABLE `beritas`
  ADD CONSTRAINT `beritas_kategori_berita_id_foreign` FOREIGN KEY (`kategori_berita_id`) REFERENCES `kategori_beritas` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
